### ISSUE TITLE
BUG: the email input field don't accept an empty space at the begin

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/authentication-server#91]
As you can see in the screenshot below, if the user try to create a new Open Data Hub user and inputs an email starting with an empty space, Keyckloack throws out the following error message:

**Invalid email address.**

![Screenshot from 2024-07-12 12-11-28](https://github.com/user-attachments/assets/c61d3d1b-b195-4c05-8d25-0c5e6e2c9e95)

The goal is to avoid this error, by trimming the email before submitting it to the database.

**Comment by dulvui** [comment]
@sseppi The email field gets now trimmed completely by removing all spaces, at the beginning/end and in-between. 
They get removed as soon as the focus of the email field is lost, so by clicking on the password field, clicking on submit or enter button.

Since this affects all tools we have, I would leave it in testing for at least a week, and test it with various browsers/devices.
But I'm pretty sure that there should not be any problems, because all JS features I used are supported in all major browsers since ~2008

**Comment by dulvui** [comment]
The fix is now in production, I tested it and it works fine.
